server:
  port: 9000
spring:
  application:
    name: zuul proxy

zuul:
  routes:
    api1:
      path: /api1/**
      url: http://localhost:9001/
    api2:
      path: /api2/**
      url: http://localhost:9002/